version: '2'
services:
  xserver:
    image: devrt/xserver
    ports:
      - "3001:80"
  workspace:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ..
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
    volumes_from:
      - xserver
    depends_on:
      - xserver
    volumes:
      - ./../:/workspace
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
